# Generated by Django 5.0.7 on 2024-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
