# Generated by Django 5.0.7 on 2024-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/home/')),
                ('welcome_01', models.TextField(max_length=30)),
                ('welcome_02', models.TextField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(upload_to='static/images/Chefs/'),
        ),
    ]
