# Generated by Django 5.0.7 on 2024-08-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_home_images_alter_chef_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_images',
            name='welcome_01',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='home_images',
            name='welcome_02',
            field=models.CharField(max_length=30),
        ),
    ]
