# Generated by Django 5.0.7 on 2024-08-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='phone',
        ),
    ]
