# Generated by Django 5.0.7 on 2024-08-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_home_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_images',
            name='image',
            field=models.ImageField(upload_to='home_images/'),
        ),
    ]
