# Generated by Django 5.0.7 on 2024-08-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_home_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='menu/dessert/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='Our Desserts')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Desssert',
        ),
        migrations.AddField(
            model_name='appetizers',
            name='description',
            field=models.TextField(default='Our Appetizers'),
        ),
        migrations.AddField(
            model_name='appetizers',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='menu/appetizer/'),
        ),
        migrations.AddField(
            model_name='home_images',
            name='description',
            field=models.TextField(default='Our Restaurant'),
        ),
        migrations.AddField(
            model_name='main_course',
            name='description',
            field=models.TextField(default='Our Main Course'),
        ),
        migrations.AddField(
            model_name='main_course',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='menu/main_course/'),
        ),
        migrations.AlterField(
            model_name='appetizers',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chef',
            name='description',
            field=models.TextField(default='Our Chef'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='chefs/'),
        ),
        migrations.AlterField(
            model_name='main_course',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
